# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import saas_agent_pb2 as saas__agent__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in saas_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentBridgeStub:
    """AgentBridge é o contrato gRPC compartilhado entre o SaaS Backend e o
    Client Agent, sustentando a comunicação entre os serviços: descoberta de
    configuração, ingestão de telemetria e motor de regras (sync + notificação
    de violações).

    A comunicação é bidirecional: cada lado expõe um servidor gRPC conforme o
    RPC (host de cada RPC documentado em proto/README.md).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAppConfig = channel.unary_unary(
                '/linx.AgentBridge/GetAppConfig',
                request_serializer=saas__agent__pb2.AppId.SerializeToString,
                response_deserializer=saas__agent__pb2.AppConfig.FromString,
                _registered_method=True)
        self.IngestTelemetry = channel.unary_unary(
                '/linx.AgentBridge/IngestTelemetry',
                request_serializer=saas__agent__pb2.TelemetryEvent.SerializeToString,
                response_deserializer=saas__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.SyncRule = channel.unary_unary(
                '/linx.AgentBridge/SyncRule',
                request_serializer=saas__agent__pb2.Rule.SerializeToString,
                response_deserializer=saas__agent__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportViolation = channel.unary_unary(
                '/linx.AgentBridge/ReportViolation',
                request_serializer=saas__agent__pb2.Violation.SerializeToString,
                response_deserializer=saas__agent__pb2.Ack.FromString,
                _registered_method=True)


class AgentBridgeServicer:
    """AgentBridge é o contrato gRPC compartilhado entre o SaaS Backend e o
    Client Agent, sustentando a comunicação entre os serviços: descoberta de
    configuração, ingestão de telemetria e motor de regras (sync + notificação
    de violações).

    A comunicação é bidirecional: cada lado expõe um servidor gRPC conforme o
    RPC (host de cada RPC documentado em proto/README.md).
    """

    def GetAppConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportViolation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAppConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppConfig,
                    request_deserializer=saas__agent__pb2.AppId.FromString,
                    response_serializer=saas__agent__pb2.AppConfig.SerializeToString,
            ),
            'IngestTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTelemetry,
                    request_deserializer=saas__agent__pb2.TelemetryEvent.FromString,
                    response_serializer=saas__agent__pb2.Ack.SerializeToString,
            ),
            'SyncRule': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncRule,
                    request_deserializer=saas__agent__pb2.Rule.FromString,
                    response_serializer=saas__agent__pb2.Ack.SerializeToString,
            ),
            'ReportViolation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportViolation,
                    request_deserializer=saas__agent__pb2.Violation.FromString,
                    response_serializer=saas__agent__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linx.AgentBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linx.AgentBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentBridge:
    """AgentBridge é o contrato gRPC compartilhado entre o SaaS Backend e o
    Client Agent, sustentando a comunicação entre os serviços: descoberta de
    configuração, ingestão de telemetria e motor de regras (sync + notificação
    de violações).

    A comunicação é bidirecional: cada lado expõe um servidor gRPC conforme o
    RPC (host de cada RPC documentado em proto/README.md).
    """

    @staticmethod
    def GetAppConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linx.AgentBridge/GetAppConfig',
            saas__agent__pb2.AppId.SerializeToString,
            saas__agent__pb2.AppConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linx.AgentBridge/IngestTelemetry',
            saas__agent__pb2.TelemetryEvent.SerializeToString,
            saas__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linx.AgentBridge/SyncRule',
            saas__agent__pb2.Rule.SerializeToString,
            saas__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportViolation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linx.AgentBridge/ReportViolation',
            saas__agent__pb2.Violation.SerializeToString,
            saas__agent__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
