[project]
name = "tenant-app-template"
version = "0.1.0"
description = ""
authors = [
    {name = "includeLuisFerreira",email = "prgluisfelipe@gmail.com"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "taskipy (>=1.14.1,<2.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "httpx2 (>=2.12.0,<3.0.0)"
]

[tool.poetry]
packages = [{include="tenant", from="src"}]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]

[tool.black]
line-length = 79
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]

# FERRAMENTAS DE LINT
lint-check = "black --check --diff . && isort --check --diff ."
mypy = "mypy src/ tests/"
flake8 = "flake8 src/ tests/"
lint = "black . && isort . && mypy src/ tests/ && flake8 src/ tests/"

# FERRAMENTAS DE TEST
pre_test = "task lint"
test = "pytest -s -x --cov=src -vv && coverage html && coverage report -m"

# FERRAMENTAS DE RUN

pre_run = "task test "
run = "poetry run uvicorn tenant.main:app --reload"
run_no_test = "poetry run uvicorn tenant.main:app --reload"
